import Head from 'next/head';
import styles from './_app';
import { HomePage } from '../../libs/home-page';

export default function Home({ data }) {
	return (
		<div className={styles.container}>
			<Head>
				<title> Event Page </title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link
					rel="icon"
					href="/favicon.ico"
				/>
			</Head>

			<HomePage data={data} />
		</div>
	);
}

export async function getServerSideProps() {
	const { events_categories } = await import('/data/data.json');

	return {
		props: {
			data: events_categories,
		},
	};
}
